### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by Tranberry** [Spyes/eldritch-old#1]
And what does it do? I assume it is related to the FFG game.

Keep it up / Oskar TRBRY

**Comment by Spyes** [comment]
It's basically a browser-based implementation of the FFG game (not official in any way). But it's currently very broken and badly written, and not complete at all so there's not much to it.... if you're still interested in checking it out, cd into the project's root dir and run nodejs from there, and in your browser go to localhost:3000

**Comment by Tranberry** [comment]
I guess that my development server interfered with it then. I love tools smart tools like this.

**Comment by Spyes** [comment]
Interfered? How so?

**Comment by Tranberry** [comment]
I meant to say I'm newb and probably messed myself. I'll come back if I find something I that I don't believe I did wrong eg. suspected bug.

**Comment by Spyes** [comment]
What were the steps that you took, and what message did you get? Maybe you didn't install a node package or something.
Anyways, if you'd like to contribute to the project - excellent! But like I said it's pretty badly written so I think we should just rewrite the whole thing

**Comment by Tranberry** [comment]
I'm barley dabbling in js - in other words I do not believe I got the knowledge to help with code, I'm a graphics man who occasionally look at code (js, phyton, php) that is not CSS or HTML.

I'm flattered but I don't have the skills needed to do anything beside graphics.

**Comment by Spyes** [comment]
Best way to learn is by doing! It's your call, if you do want to join up you're more than welcome and I will be more than happy to guide you along :)
In any case, because this isn't an official project, I'm not legally allowed to use the graphics from the game. So if you want to contribute graphics, that would also be awesome! (World map, investigators, cards, etc.) No pressure though :) I need to find time to work on this anyways...

**Comment by Tranberry** [comment]
I could do some temporary replacement graphic if you want to have that, like you there are so much to do so little time :hourglass_flowing_sand: .

I've already started on a world map, with a denotation on started. And I usually try to use cc-by if not cc0 on my own work. If I'm not doing it professionally.

**Comment by Tranberry** [comment]
You might have to zoom out but this is what I mean when I say that I've started on a map. http://imgh.us/exportSVG1.svg

**Comment by Spyes** [comment]
You did it as SVG! I can't tell you how much I appreciate that - SVG is the way to go! good work!
And hey, it's looking really good! but maybe make the major city markers a bit smaller? Other than that - really cool!

**Comment by Tranberry** [comment]
Yeah I know SVG is the future!
City markers are just placeholders atm, it is nowhere near done, I'd say it's about 5-10% done.

**Comment by Spyes** [comment]
Well, it looks great! And if this is only 5-10% done, I can't wait to see it at 100% :D
